### ISSUE TITLE
Allergies for eVACDOC (François von Kaenel, BFH)

### ISSUE THREAD

**Issue by ig-feedback** [ehealthsuisse/ch-vacd#17] opened 2021-03-15 16:51 UTC
ch.fhir.ig.ch-vacd#0.1.0 /ValueSet-ch-vacd-allergies-immunizations-vs.html

The list is very short, this is probably on work. Or does a "complete" list already exist?

François von Kaenel, BFH

**Comment by ralych** [comment] 2021-03-17 06:23
see #50 and #57

**Comment by eHealth-Suisse** [comment] 2021-03-17 16:15
and see #15 for yet another duplicate . will be worked on on issue #57

**Comment by eHealth-Suisse** [comment] 2021-05-21 13:58
duplicate of #15, #17, #57, can be closed accordingly. Value Set has been enlarged, see http://build.fhir.org/ig/ehealthsuisse/ch-vacd/ValueSet-ch-vacd-immunization-allergyintolerances-vs.html 
@vnf1  zur Kenntnis und für allfällige Einwände.

**Closed by eHealth-Suisse** 2021-05-21 13:58 UTC
Labels: duplicate, informative ballot v0.1.0, review-fix, wontfix
